In [1]:
import transitfeed

In [4]:
path_small = r"D:\dev\intermodalrouting\src\test\resources\tt_gtfs\gtfsfp20192018-12-05_small.zip"
path_ch = r"D:\data\90_divers\gtfs (2).zip"

In [5]:
schedule_small = transitfeed.loader.Loader(path_small).Load()

routes.txt:2 column route_type
Invalid value 102 in field route_type
routes.txt:3 column route_type
Invalid value 1300 in field route_type
routes.txt:4 column route_type
Invalid value 1000 in field route_type
routes.txt:5 column route_type
Invalid value 700 in field route_type
routes.txt:6 column route_type
Invalid value 700 in field route_type
feed_info.txt:1
Each line must end with CR LF or LF except for the last line of the file. This
line ends with "\r\r\n".
feed_info.txt:2
Each line must end with CR LF or LF except for the last line of the file. This
line ends with "\r\r\n".

In [6]:
schedule_small.GetStopList()[0]

[<Stop [('location_type', 0), ('parent_station', u'8504100P'), ('stop_id', u'8504100:0:3'), ('stop_lat', 46.8033890512149), ('stop_lon', 7.1510208539232), ('stop_name', u'Fribourg/Freiburg')]>,
 <Stop [('location_type', 0), ('parent_station', u'8504100P'), ('stop_id', u'8504100:0:2'), ('stop_lat', 46.8034505412191), ('stop_lon', 7.1510208539232), ('stop_name', u'Fribourg/Freiburg')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572656'), ('stop_lat', 47.3029976490063), ('stop_lon', 8.04573389387795), ('stop_name', u'Sch\xf6ftland, Dreistein')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572657'), ('stop_lat', 47.3027235233005), ('stop_lon', 8.04211368328244), ('stop_name', u'Sch\xf6ftland, Pikardie')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:34'), ('stop_lat', 47.3790278168616), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8502113P'), ('stop_id', u'8502113:0:3'), ('stop_lat', 47.3910219316618), ('stop_lon', 8.0507824257754), ('stop_name', u'Aarau')]>,
 <Stop [('location_type', 0), ('parent_station', u'8501026P'), ('stop_id', u'8501026:0:2'), ('stop_lat', 46.2325925185326), ('stop_lon', 6.11198448040172), ('stop_name', u'Gen\xe8ve-A\xe9roport')]>,
 <Stop [('location_type', 0), ('parent_station', u'8501026P'), ('stop_id', u'8501026:0:1'), ('stop_lat', 46.2326546578844), ('stop_lon', 6.11198448040172), ('stop_name', u'Gen\xe8ve-A\xe9roport')]>,
 <Stop [('location_type', 0), ('parent_station', u'8573213P'), ('stop_id', u'8573213:0:A'), ('stop_lat', 47.4449616782108), ('stop_lon', 8.57069137968479), ('stop_name', u'Z\xfcrich Flughafen, Werft')]>,
 <Stop [('location_type', 0), ('parent_station', u'8573213P'), ('stop_id', u'8573213:0:C'), ('stop_lat', 47.4449009252815), ('stop_lon', 8.57069137968479), ('stop_name', u'Z\xfcrich Flughafen, Werft')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502886'), ('stop_lat', 47.272201401172), ('stop_lon', 8.06472427898688), ('stop_name', u'Kirchleerau-Moosleerau, Post')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502887'), ('stop_lat', 47.2511870268282), ('stop_lon', 8.04565304550236), ('stop_name', u'Reitnau, Post')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8504564'), ('stop_lat', 46.8522084193377), ('stop_lon', 6.83835323608903), ('stop_name', u'Estavayer-le-Lac LNM')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590889'), ('stop_lat', 47.4164973252936), ('stop_lon', 8.57907266128679), ('stop_name', u'Wallisellen, Herti')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590558'), ('stop_lat', 47.40238097988), ('stop_lon', 8.62740202357915), ('stop_name', u'D\xfcbendorf, Flugplatz')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572661'), ('stop_lat', 47.2804719606536), ('stop_lon', 8.0598194775349), ('stop_name', u'Kirchleerau, Fabrik Hunziker')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572660'), ('stop_lat', 47.2828303873682), ('stop_lon', 8.04501524165055), ('stop_name', u'Staffelbach, Suhrenbr\xfccke')]>,
 <Stop [('location_type', 0), ('parent_station', u'8500218P'), ('stop_id', u'8500218:0:7'), ('stop_lat', 47.3522319182299), ('stop_lon', 7.90768978414808), ('stop_name', u'Olten')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590881'), ('stop_lat', 47.4143089924294), ('stop_lon', 8.58581900907146), ('stop_name', u'Wallisellen, Belair')]>,
 <Stop [('location_type', 0), ('parent_station', u'8500218P'), ('stop_id', u'8500218:0:8'), ('stop_lat', 47.3520493381822), ('stop_lon', 7.90768978414808), ('stop_name', u'Olten')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572669'), ('stop_lat', 47.2335741315613), ('stop_lon', 8.07727374350777), ('stop_name', u'Triengen, Dorf')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572668'), ('stop_lat', 47.23648968966), ('stop_lon', 8.07484829224031), ('stop_name', u'Triengen, K\xe4serei')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590554'), ('stop_lat', 47.3969997232025), ('stop_lon', 8.61648749287557), ('stop_name', u'D\xfcbendorf, City Center')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590884'), ('stop_lat', 47.4117011103409), ('stop_lon', 8.59727252894558), ('stop_name', u'Wallisellen, Florastrasse')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590548'), ('stop_lat', 47.4007392988171), ('stop_lon', 8.62425792008429), ('stop_name', u'D\xfcbendorf, Bahnhof Nord')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590576'), ('stop_lat', 47.3967017618595), ('stop_lon', 8.61360390081315), ('stop_name', u'D\xfcbendorf, Meiershofstrasse')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8530106'), ('stop_lat', 46.1447131023157), ('stop_lon', 7.23308195513894), ('stop_name', u'La Tzoumaz')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8530105'), ('stop_lat', 46.1223648337497), ('stop_lon', 7.21898738832914), ('stop_name', u'Savoleyres')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:15'), ('stop_lat', 47.3784803529949), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:14'), ('stop_lat', 47.3783586935859), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:16'), ('stop_lat', 47.3784195233255), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:11'), ('stop_lat', 47.3795144466376), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:10'), ('stop_lat', 47.3794536181612), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:13'), ('stop_lat', 47.3785411825942), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:12'), ('stop_lat', 47.3786020121232), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:10'), ('stop_lat', 46.9495608430423), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8594553'), ('stop_lat', 47.4326456250948), ('stop_lon', 8.57155376235766), ('stop_name', u'Opfikon, Schwimmbad')]>,
 <Stop [('location_type', 0), ('parent_station', u'8501026P'), ('stop_id', u'8501026:0:3'), ('stop_lat', 46.2327167971658), ('stop_lon', 6.11198448040172), ('stop_name', u'Gen\xe8ve-A\xe9roport')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590575'), ('stop_lat', 47.398507746605), ('stop_lon', 8.62029634968077), ('stop_name', u'D\xfcbendorf, Lindenplatz')]>,
 <Stop [('location_type', 0), ('parent_station', u'8501120P'), ('stop_id', u'8501120:0:5'), ('stop_lat', 46.5170280082488), ('stop_lon', 6.62909069062426), ('stop_name', u'Lausanne')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8573214'), ('stop_lat', 47.4402470423624), ('stop_lon', 8.5716885096503), ('stop_name', u'Kloten, Balsberg Hardacher')]>,
 <Stop [('location_type', 0), ('parent_station', u'8501120P'), ('stop_id', u'8501120:0:1'), ('stop_lat', 46.5169661916384), ('stop_lon', 6.62909069062426), ('stop_name', u'Lausanne')]>,
 <Stop [('location_type', 0), ('parent_station', u'8501008P'), ('stop_id', u'8501008:0:6'), ('stop_lat', 46.2102675118531), ('stop_lon', 6.14245533484329), ('stop_name', u'Gen\xe8ve')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590579'), ('stop_lat', 47.4028430734713), ('stop_lon', 8.6013598634889), ('stop_name', u'D\xfcbendorf, Neugut S\xfcd')]>,
 <Stop [('location_type', 0), ('parent_station', u'8501008P'), ('stop_id', u'8501008:0:2'), ('stop_lat', 46.2103296764772), ('stop_lon', 6.14245533484329), ('stop_name', u'Gen\xe8ve')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590556'), ('stop_lat', 47.4058709022332), ('stop_lon', 8.63099528471612), ('stop_name', u'D\xfcbendorf, Eglish\xf6lzli')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502088'), ('stop_lat', 47.2856883914951), ('stop_lon', 8.04198791914265), ('stop_name', u'Staffelbach, Gemeindehaus')]>,
 <Stop [('location_type', 0), ('parent_station', u'8573205P'), ('stop_id', u'8573205:0:K'), ('stop_lat', 47.4508057819635), ('stop_lon', 8.56372943623189), ('stop_name', u'Z\xfcrich Flughafen, Bahnhof')]>,
 <Stop [('location_type', 0), ('parent_station', u'8573205P'), ('stop_id', u'8573205:0:J'), ('stop_lat', 47.4508665280728), ('stop_lon', 8.56372943623189), ('stop_name', u'Z\xfcrich Flughafen, Bahnhof')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8580536'), ('stop_lat', 47.4308408107752), ('stop_lon', 8.57371870219269), ('stop_name', u'Opfikon, Schulstrasse')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8581347'), ('stop_lat', 47.2678980049136), ('stop_lon', 8.0604123656225), ('stop_name', u'Moosleerau, Unterdorf')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8581055'), ('stop_lat', 47.2580098399457), ('stop_lon', 8.04432353888168), ('stop_name', u'Attelwil, Schule')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502095'), ('stop_lat', 47.2383926452432), ('stop_lon', 8.05104293720783), ('stop_name', u'Winikon, Post')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502097'), ('stop_lat', 47.2691476106984), ('stop_lon', 8.06461648115277), ('stop_name', u'Moosleerau, Abzw.')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502096'), ('stop_lat', 47.2609301498905), ('stop_lon', 8.04470981445391), ('stop_name', u'Attelwil, alte Post')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8587651'), ('stop_lat', 47.4092086081654), ('stop_lon', 8.59554776359983), ('stop_name', u'Wallisellen, Glatt (Bus)')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8587652'), ('stop_lat', 47.4056277095638), ('stop_lon', 8.59100228826155), ('stop_name', u'Z\xfcrich, Altried')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8587654'), ('stop_lat', 47.434511142518), ('stop_lon', 8.56762812456551), ('stop_name', u'Glattbrugg, Glatthof')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8587655'), ('stop_lat', 47.4127223942356), ('stop_lon', 8.59252942424477), ('stop_name', u'Wallisellen, Bahnhof')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503016P'), ('stop_id', u'8503016:0:1'), ('stop_lat', 47.4504413038344), ('stop_lon', 8.56238196330552), ('stop_name', u'Z\xfcrich Flughafen')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590510'), ('stop_lat', 47.4043813295105), ('stop_lon', 8.59605082015901), ('stop_name', u'D\xfcbendorf, Sport Heerensch\xfcrli')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:33'), ('stop_lat', 47.3790886458292), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u'8503000P'), ('stop_id', u'8503000:0:32'), ('stop_lat', 47.3792103035539), ('stop_lon', 8.54019357578468), ('stop_name', u'Z\xfcrich HB')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8504556'), ('stop_lat', 46.8486451165296), ('stop_lon', 6.72029664143361), ('stop_name', u'Concise LNM')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8504557'), ('stop_lat', 46.8059777195849), ('stop_lon', 6.64287983023742), ('stop_name', u'Grandson LNM')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8504555'), ('stop_lat', 46.8898543914967), ('stop_lon', 6.77499505909126), ('stop_name', u'St-Aubin NE LNM')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8504558'), ('stop_lat', 46.7871962876262), ('stop_lon', 6.64049929473417), ('stop_name', u'Yverdon-les-Bains LNM')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502089'), ('stop_lat', 47.2919583968384), ('stop_lon', 8.03937382166549), ('stop_name', u'Wittwil, K\xe4serei')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8504243'), ('stop_lat', 46.8780414353611), ('stop_lon', 6.76125083524232), ('stop_name', u'Vaumarcus d\xe9barcad\xe8re')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8580443'), ('stop_lat', 47.4363765938092), ('stop_lon', 8.56892169857482), ('stop_name', u'Glattbrugg, Riethofstrasse')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8502748'), ('stop_lat', 47.276358174077), ('stop_lon', 8.06298154733544), ('stop_name', u'Kirchleerau, Abzw.')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590582'), ('stop_lat', 47.4001494972038), ('stop_lon', 8.60727077805923), ('stop_name', u'D\xfcbendorf, Ringstrasse')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:8'), ('stop_lat', 46.9491315819468), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:5'), ('stop_lat', 46.9494381973663), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:4'), ('stop_lat', 46.9491929051712), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:7'), ('stop_lat', 46.9493155514093), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:6'), ('stop_lat', 46.9493768744229), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:3'), ('stop_lat', 46.9494995202394), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u'8507000P'), ('stop_id', u'8507000:0:2'), ('stop_lat', 46.9488862883465), ('stop_lon', 7.43911954873327), ('stop_name', u'Bern')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590748'), ('stop_lat', 47.4280392760524), ('stop_lon', 8.57433853973882), ('stop_name', u'Opfikon, Neuwiesen')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590741'), ('stop_lat', 47.4250370321119), ('stop_lon', 8.57520990556454), ('stop_name', u'Opfikon, Austrasse')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572648'), ('stop_lat', 47.3055987266341), ('stop_lon', 8.05007275670085), ('stop_name', u'Sch\xf6ftland, Bahnhof')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590901'), ('stop_lat', 47.4104305568981), ('stop_lon', 8.6458893521289), ('stop_name', u"Wangen b D'dorf, Dorfplatz")]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590902'), ('stop_lat', 47.4103211298091), ('stop_lon', 8.64272728232836), ('stop_name', u"Wangen b D'dorf, H\xe4tzelwisen")]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590903'), ('stop_lat', 47.4079562332809), ('stop_lon', 8.64599714996301), ('stop_name', u"Wangen b D'dorf, Oberdorf")]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590904'), ('stop_lat', 47.4093301963741), ('stop_lon', 8.64170320290432), ('stop_name', u"Wangen b D'dorf, Stierwisen")]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590905'), ('stop_lat', 47.4124549170346), ('stop_lon', 8.63986165657162), ('stop_name', u"Wangen b D'dorf, Weidli")]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8590906'), ('stop_lat', 47.4080595857337), ('stop_lon', 8.63758891890248), ('stop_name', u'Wangen, Flugsicherungsstrasse')]>,
 <Stop [('location_type', 0), ('parent_station', u''), ('stop_id', u'8572666'), ('stop_lat', 47.247400260633), ('stop_lon', 8.04871630062164), ('stop_name', u'Reitnau, Unterdorf')]>]

In [7]:
schedule_ch = transitfeed.loader.Loader(path_ch).Load()

calendar.txt:5
Service period with service_id "156501_merged_1171035" doesn't have service on
any days of the week.
calendar.txt:7
Service period with service_id "10902_merged_1171042" doesn't have service on
any days of the week.
calendar.txt:70
Service period with service_id "6503_merged_1171118" doesn't have service on
any days of the week.
calendar.txt:107
Service period with service_id "115101_merged_1171014" doesn't have service on
any days of the week.
calendar.txt:172
Service period with service_id "10901_merged_1171040" doesn't have service on
any days of the week.
calendar.txt:21
Service period with service_id "27402_merged_1171008" doesn't have service on
any days of the week.
calendar.txt:23
Service period with service_id "169005" doesn't have service on any days of
the week.
calendar.txt:28
Service period with service_id "27503_merged_1171032" doesn't have service on
any days of the week.
calendar.txt:29
Service period with service_id "6301_merged_1171023" doesn't have service on
any days of the week.
calendar.txt:31
Service period with service_id "27502_merged_1171115" doesn't have service on
any days of the week.
calendar.txt:36
Service period with service_id "27501_merged_1171034" doesn't have service on
any days of the week.
calendar.txt:43
Service period with service_id "75301_merged_1171006" doesn't have service on
any days of the week.
calendar.txt:48
Service period with service_id "53101_merged_1171083" doesn't have service on
any days of the week.
calendar.txt:53
Service period with service_id "1903_merged_1171127" doesn't have service on
any days of the week.
calendar.txt:58
Service period with service_id "53501_merged_1171059" doesn't have service on
any days of the week.
calendar.txt:60
Service period with service_id "16901_merged_1171144" doesn't have service on
any days of the week.
calendar.txt:61
Service period with service_id "89202_merged_1171162" doesn't have service on
any days of the week.
calendar.txt:63
Service period with service_id "27503_merged_1171114" doesn't have service on
any days of the week.
calendar.txt:64
Service period with service_id "31101_merged_1171101" doesn't have service on
any days of the week.
calendar.txt:26
Service period with service_id "157605_merged_1171129" doesn't have service on
any days of the week.
calendar.txt:69
Service period with service_id "125101_merged_1171028" doesn't have service on
any days of the week.
calendar.txt:71
Service period with service_id "31104" doesn't have service on any days of the
week.
calendar.txt:117
Service period with service_id "6202_merged_1171053" doesn't have service on
any days of the week.
calendar.txt:33
Service period with service_id "6304" doesn't have service on any days of the
week.
calendar.txt:77
Service period with service_id "6201_merged_1171134" doesn't have service on
any days of the week.
calendar.txt:78
Service period with service_id "6302_merged_1171025" doesn't have service on
any days of the week.
calendar.txt:86
Service period with service_id "16903_merged_1171060" doesn't have service on
any days of the week.
calendar.txt:87
Service period with service_id "16902_merged_1171143" doesn't have service on
any days of the week.
calendar.txt:88
Service period with service_id "89203_merged_1171081" doesn't have service on
any days of the week.
calendar.txt:89
Service period with service_id "1902_merged_1171044" doesn't have service on
any days of the week.
calendar.txt:92
Service period with service_id "27504" doesn't have service on any days of the
week.
calendar.txt:95
Service period with service_id "6504" doesn't have service on any days of the
week.
calendar.txt:96
Service period with service_id "16903_merged_1171142" doesn't have service on
any days of the week.
calendar.txt:97
Service period with service_id "10904" doesn't have service on any days of the
week.
calendar.txt:103
Service period with service_id "89201_merged_1171079" doesn't have service on
any days of the week.
calendar.txt:104
Service period with service_id "89202_merged_1171080" doesn't have service on
any days of the week.
calendar.txt:105
Service period with service_id "52901_merged_1171050" doesn't have service on
any days of the week.
calendar.txt:9
Service period with service_id "53201_merged_1171026" doesn't have service on
any days of the week.
calendar.txt:108
Service period with service_id "6502_merged_1171119" doesn't have service on
any days of the week.
calendar.txt:112
Service period with service_id "31101_merged_1171019" doesn't have service on
any days of the week.
calendar.txt:114
Service period with service_id "201_merged_1171070" doesn't have service on
any days of the week.
calendar.txt:115
Service period with service_id "1904" doesn't have service on any days of the
week.
calendar.txt:127
Service period with service_id "1901_merged_1171046" doesn't have service on
any days of the week.
calendar.txt:120
Service period with service_id "1902_merged_1171126" doesn't have service on
any days of the week.
calendar.txt:123
Service period with service_id "27401_merged_1171010" doesn't have service on
any days of the week.
calendar.txt:119
Service period with service_id "6204" doesn't have service on any days of the
week.
calendar.txt:157
Service period with service_id "35002_merged_1171082" doesn't have service on
any days of the week.
calendar.txt:132
Service period with service_id "6501_merged_1171120" doesn't have service on
any days of the week.
calendar.txt:135
Service period with service_id "6301_merged_1171105" doesn't have service on
any days of the week.
calendar.txt:136
Service period with service_id "6303_merged_1171024" doesn't have service on
any days of the week.
calendar.txt:138
Service period with service_id "27403_merged_1171009" doesn't have service on
any days of the week.
calendar.txt:139
Service period with service_id "203_merged_1171154" doesn't have service on
any days of the week.
calendar.txt:142
Service period with service_id "53401_merged_1171002" doesn't have service on
any days of the week.
calendar.txt:144
Service period with service_id "31102_merged_1171102" doesn't have service on
any days of the week.
calendar.txt:171
Service period with service_id "204" doesn't have service on any days of the
week.
calendar.txt:130
Service period with service_id "54401_merged_1171069" doesn't have service on
any days of the week.
calendar.txt:146
Service period with service_id "31102_merged_1171020" doesn't have service on
any days of the week.
calendar.txt:152
Service period with service_id "201_merged_1171152" doesn't have service on
any days of the week.
calendar.txt:153
Service period with service_id "1903_merged_1171045" doesn't have service on
any days of the week.
calendar.txt:118
Service period with service_id "6203_merged_1171136" doesn't have service on
any days of the week.
calendar.txt:159
Service period with service_id "6503_merged_1171036" doesn't have service on
any days of the week.
calendar.txt:162
Service period with service_id "16904" doesn't have service on any days of the
week.
calendar.txt:164
Service period with service_id "6202_merged_1171135" doesn't have service on
any days of the week.
calendar.txt:165
Service period with service_id "10903_merged_1171041" doesn't have service on
any days of the week.
calendar.txt:99
Service period with service_id "3701_merged_1171075" doesn't have service on
any days of the week.
calendar.txt:80
Service period with service_id "27402_merged_1171090" doesn't have service on
any days of the week.
calendar.txt:82
Service period with service_id "6203_merged_1171054" doesn't have service on
any days of the week.
calendar.txt:175
Service period with service_id "89203_merged_1171163" doesn't have service on
any days of the week.
calendar.txt:176
Service period with service_id "31103_merged_1171103" doesn't have service on
any days of the week.
calendar.txt:179
Service period with service_id "53001_merged_1171011" doesn't have service on
any days of the week.
calendar.txt:180
Service period with service_id "16902_merged_1171061" doesn't have service on
any days of the week.
calendar.txt:181
Service period with service_id "27501_merged_1171116" doesn't have service on
any days of the week.
calendar.txt:182
Service period with service_id "3601_merged_1171055" doesn't have service on
any days of the week.
calendar.txt:183
Service period with service_id "89204" doesn't have service on any days of the
week.
calendar.txt:184
Service period with service_id "27403_merged_1171091" doesn't have service on
any days of the week.
calendar.txt:185
Service period with service_id "3104" doesn't have service on any days of the
week.
calendar.txt:186
Service period with service_id "6502_merged_1171037" doesn't have service on
any days of the week.
calendar.txt:187
Service period with service_id "54401_merged_1171151" doesn't have service on
any days of the week.
stops.txt:49 column stop_desc
Invalid value 7990 OSWEGO RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:51 column stop_desc
Invalid value 7376 OSWEGO RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:64 column stop_desc
Invalid value MCCOOL AVE & E YATES ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:97 column stop_desc
Invalid value S SALINA ST & S WARREN ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:209 column stop_desc
Invalid value S SALINA ST & DORWIN AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:257 column stop_desc
Invalid value BRIDGE ST & E 2ND ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:343 column stop_desc
Invalid value S SALINA ST & KIRK AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:346 column stop_desc
Invalid value S SALINA ST & E BORDEN AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:365 column stop_desc
Invalid value W MANLIUS ST & KINNE ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:366 column stop_desc
Invalid value KINNE ST & W MANLIUS ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:368 column stop_desc
Invalid value W MANLIUS ST & CHARLES ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:407 column stop_desc
Invalid value S SALINA ST & E BRIGHTON AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:446 column stop_desc
Invalid value 4789 STATE ROUTE 3 in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:447 column stop_desc
Invalid value 4788 STATE ROUTE 3 in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:450 column stop_desc
Invalid value 4506 STATE ROUTE 3 in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:451 column stop_desc
Invalid value 3775 STATE ROUTE 3 in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:452 column stop_desc
Invalid value 3774 STATE ROUTE 3 in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:585 column stop_desc
Invalid value E GLEN AVE & S SALINA ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:602 column stop_desc
Invalid value S SALINA ST & CORTLAND AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:626 column stop_desc
Invalid value BUNNER ST & MAPLE ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:662 column stop_desc
Invalid value W MANLIUS ST & BALL ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:674 column stop_desc
Invalid value ONEIDA HALL & ONONDAGA HALL in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:677 column stop_desc
Invalid value S SALINA ST & AMIDON DR in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:678 column stop_desc
Invalid value S SALINA ST & RICHFIELD AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:679 column stop_desc
Invalid value S 11TH ST & EMERY ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:680 column stop_desc
Invalid value MAPLE ST & BUNNER ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:681 column stop_desc
Invalid value EAST AVE & WALNUT ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:682 column stop_desc
Invalid value S SALINA ST & CONIFER DR in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:700 column stop_desc
Invalid value W ONONDAGA ST & KANDACE ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:733 column stop_desc
Invalid value HARTWELL AVE & E HEMAN ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:734 column stop_desc
Invalid value E IRVING ST & HARTWELL AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:739 column stop_desc
Invalid value E SENECA TPKE & LAFAYETTE RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:746 column stop_desc
Invalid value ATLANTIC AVE & EMPIRE AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:779 column stop_desc
Invalid value S SALINA ST & EDWARD PKWY in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:782 column stop_desc
Invalid value S SALINA ST & BELLE AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:839 column stop_desc
Invalid value E WASHINGTON ST & BREWERTON RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:905 column stop_desc
Invalid value VALLEY DR & W SENECA TPKE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:907 column stop_desc
Invalid value VALLEY DR & ATLANTIC AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:913 column stop_desc
Invalid value JAMES ST & MILDRED AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:965 column stop_desc
Invalid value ATLANTIC AVE & GIRARD AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:975 column stop_desc
Invalid value W SENECA TPKE & MILBURN DR in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:976 column stop_desc
Invalid value S SALINA ST & RICHFIELD AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:979 column stop_desc
Invalid value VALLEY DR & ENGLEWOOD AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:983 column stop_desc
Invalid value KINNE ST & SANDERS CREEK PKWY in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:984 column stop_desc
Invalid value OLD COLLAMER RD S & CARRIER PKWY in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:985 column stop_desc
Invalid value OLD COLLAMER RD S & COURT STREET RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1002 column stop_desc
Invalid value S SALINA ST & BALLANTYNE RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1027 column stop_desc
Invalid value FILLMORE AVE & S SALINA ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1028 column stop_desc
Invalid value WIDEWATERS PKWY & TOWPATH RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1049 column stop_desc
Invalid value HARTWELL AVE & E IRVING ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1052 column stop_desc
Invalid value S SALINA ST & W BEARD AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1120 column stop_desc
Invalid value S SALINA ST & WOOD AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1224 column stop_desc
Invalid value S SALINA ST & E MATSON AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1346 column stop_desc
Invalid value S SALINA ST & MCKINLEY AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1347 column stop_desc
Invalid value JAMES ST & SEDGWICK DR in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1348 column stop_desc
Invalid value S SALINA ST & AMHERST AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1350 column stop_desc
Invalid value S SALINA ST & WARNER AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1405 column stop_desc
Invalid value JAMES ST & KINNE ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1406 column stop_desc
Invalid value KINNE ST & JAMES ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1407 column stop_desc
Invalid value JAMES ST & EAST AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1408 column stop_desc
Invalid value JAMES ST & EAST AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1607 column stop_desc
Invalid value S SALINA ST & W LAFAYETTE AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1615 column stop_desc
Invalid value S SALINA ST & W CORNING AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1629 column stop_desc
Invalid value E FAYETTE ST & MONTGOMERY ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1633 column stop_desc
Invalid value JAMES ST & COLFAX AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1636 column stop_desc
Invalid value JAMES ST & WEST AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1642 column stop_desc
Invalid value BUTTERNUT ST & GRANT BLVD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1722 column stop_desc
Invalid value S SALINA ST & MCKINLEY AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1849 column stop_desc
Invalid value S SALINA ST & W CALTHROP AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1880 column stop_desc
Invalid value S SALINA ST & PARRISH LN in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1887 column stop_desc
Invalid value S SALINA ST & W WARRINGTON RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1891 column stop_desc
Invalid value S SALINA ST & HARDING PL in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1892 column stop_desc
Invalid value S SALINA ST & W CHELTENHAM RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1921 column stop_desc
Invalid value GRAND AVE & S AVERY AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:1942 column stop_desc
Invalid value S SALINA ST & E CASTLE ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:2005 column stop_desc
Invalid value E GLEN AVE & OTTO ST in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:2006 column stop_desc
Invalid value E GLEN AVE & STEVENS AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:2046 column stop_desc
Invalid value VALLEY DR & FISH AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:2142 column stop_desc
Invalid value S SALINA ST & E ROSWELL AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:2157 column stop_desc
Invalid value JAMES ST & MARLBOROUGH RD in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:2160 column stop_desc
Invalid value JAMES ST & LILLIAN AVE in field stop_desc
stop_desc should not be the same as stop_name
stops.txt:2289 column stop_desc
Invalid value VALLEY DR & CORTLAND PL in field stop_desc
stop_desc should not be the same as stop_name

In [8]:
print len(schedule_ch.GetStopList())

6456

In [17]:
schedule_ch.GetStopList()[3456].stop_name

u'Teall Ave & Schuler St'

In [35]:
for id, sp in schedule_small.service_periods.iteritems():
    print id, len(sp.ActiveDates())

TA+b02lk 1
TA+b00va 3
TA+b00xp 370
TA+b01po 59
TA+b04t2 346
TA+b01pm 2
TA+b01pj 2
TA+b03e9 264
TA+b00xn 1
TA+b03ur 117
TA+b00io 202
TA+b032h 1
TA+b01u0 203
TA+b00ie 104
TA+b015v 7
TA+b0001 371
TA+b04t8 12
TA+b04t6 201
TA+b04t7 161
TA+b04t4 59
TA+b04t5 197
TA+b00cw 1
TA+b04t3 12
TA+b000f 253
TA+b01ej 2
TA+b020b 1
TA+b02yb 104
TA+b00si 370
TA+b00m3 1
TA+b02q7 5
TA+b04cn 69
TA+b01qo 160
TA+b04eo 358
TA+b008g 51
TA+b000x 53
TA+b0016 65
TA+b00ue 4
TA+b01is 254
TA+b02ka 6
TA+b02ro 100
TA+b041r 51
TA+b02y6 1
TA+b01fz 7
TA+b04hn 2
TA+b04co 72
TA+b02i1 1